name: bainite-segmentation
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - numpy
  - matplotlib
  - pillow
  - scikit-image
  - opencv
  - jupyter
  - pip:
      - -r requirements.txt